"use client";
import {useEffect,useMemo,useState} from "react";
const missions=[
["SEP 10","MISSION 001","WATERPROOF","◌",<><p>Bring:</p><ul><li>Waterproof shoes</li><li>A waterproof jacket</li><li>Waterproof pants</li></ul><p className="muted">You're going to want to stay dry.</p><p className="classified">That's all I'm telling you.</p></>],
["SEP 11","MISSION 002","LAYERS","✦",<><p>Pack clothes you can easily layer.</p><ul><li>Long sleeves</li><li>Sweaters</li><li>A warm mid-layer</li></ul><p className="muted">You'll want options.</p></>],
["SEP 12","MISSION 003","CAPTURE","⌁",<><p>Bring your:</p><ul><li>Camera</li><li>Drone</li><li>Extra batteries / chargers</li></ul><p className="muted">You're going to want to capture this one.</p><p className="classified">Trust me.</p></>],
["SEP 13","MISSION 004","SWIM","≈",<><p>Pack a swimsuit.</p><p className="muted">Yes, you actually need one.</p><p className="classified">Don't ask why.</p></>],
["SEP 14","MISSION 005","DAY BAG","▢",<><p>Bring a small backpack or crossbody bag for daytime exploring.</p><p className="muted">You'll want your essentials close by.</p></>],
["SEP 15","MISSION 006","COMFORT","⌂",<><p>Pack comfortable clothes and shoes.</p><p className="muted">There will be plenty of exploring.</p><p className="classified">You'll be glad you did.</p></>]
];
const revealAt="2026-09-16T19:00:00-04:00";
function cd(ms:number){const t=Math.max(0,Math.floor(ms/1000));return[Math.floor(t/86400),Math.floor(t%86400/3600),Math.floor(t%3600/60),t%60]}
export default function Home(){
 const[now,setNow]=useState<Date|null>(null),[tick,setTick]=useState(0),[egg,setEgg]=useState<string|null>(null),[open,setOpen]=useState<number|null>(null);
 useEffect(()=>{fetch("/api/time",{cache:"no-store"}).then(r=>r.json()).then(x=>setNow(new Date(x.now))).catch(()=>setNow(new Date()));},[]);
 useEffect(()=>{const id=setInterval(()=>setTick(x=>x+1),1000);return()=>clearInterval(id)},[]);
 const current=useMemo(()=>now?new Date(now.getTime()+tick*1000):null,[now,tick]);
 const reveal=new Date(revealAt), revealed=!!current&&current>=reveal, left=current?cd(reveal.getTime()-current.getTime()):null;
 const unlocked=(i:number)=>!!current&&current>=new Date(`2026-09-${String(10+i).padStart(2,"0")}T09:00:00-04:00`);
 const show=(x:string)=>{setEgg(x);setTimeout(()=>setEgg(null),2600)};
 if(revealed)return <main className="reveal"><div className="stars"/><div className="aurora a1"/><div className="aurora a2"/><section className="revealCard"><div className="eyebrow">CLASSIFIED DESTINATION // UNLOCKED</div><p className="intro">You followed the instructions.</p><p className="intro">You packed the right things.</p><p className="intro">And somehow, you still didn't know.</p><div className="word">{["I","C","E","L","A","N","D"].map((x,i)=><span key={x} style={{animationDelay:`${i*.08}s`}}>{x}</span>)}</div><div className="flag">🇮🇸</div><h1>You're going to Iceland.</h1><p className="dates">SEPTEMBER 16–20, 2026</p><div className="divider"/><p className="final">We leave tonight.<br/>Happy 30th, Elvir. ❤️</p><p className="small">YOUR BIRTHDAY ADVENTURE STARTS NOW.</p></section></main>;
 return <main className="page"><header className="hero"><button className="secret" aria-label="secret" onClick={()=>show("Nice try. The destination remains classified.")}/><div className="eyebrow">ELVIR // 30TH BIRTHDAY</div><h1>Your birthday<br/><em>mission</em> begins.</h1><p className="heroCopy">Your destination is classified. Your job is simple:<br/>follow the instructions, pack accordingly, and ask no questions.</p><div className="status"><b/> DESTINATION: CLASSIFIED</div></header>
 <section className="countdownWrap"><div className="countLabel">TIME UNTIL DESTINATION UNLOCK</div><div className="countdown">{left?<>{left.map((x,i)=><span key={i} className={i===0?"days":""}><strong>{String(x).padStart(2,"0")}</strong><small>{["DAYS","HRS","MIN","SEC"][i]}</small></span>).reduce((a,b,i)=>i?[...a,<i key={"c"+i}>:</i>,b]:[b],[])}</>:<span>SYNCING WITH MISSION CONTROL…</span>}</div><div className="unlock">SEPTEMBER 16 // 7:00 PM EASTERN</div></section>
 <section className="missions"><div className="heading"><span>01—06</span><div><h2>Daily instructions</h2><p>New information unlocks each morning.</p></div></div><div className="grid">{missions.map((m,i)=>{const ok=unlocked(i),isOpen=open===i;return <article key={m[0] as string} className={`card ${ok?"available":"locked"}`} onClick={()=>ok&&setOpen(isOpen?null:i)}><div className="top"><span>{m[0]}</span><span>{ok?m[3]:"🔒"}</span></div><div className="num">{m[1]}</div><h3>{ok?m[2]:"CLASSIFIED"}</h3>{ok?<div className="body">{m[4]}</div>:<p className="lockedCopy">This mission hasn't unlocked yet.<br/><span>Come back soon.</span></p>}{ok&&<div className="tap">{isOpen?"CLOSE ↑":"OPEN ↓"}</div>}</article>})}</div></section>
 <section className="teaser"><button onClick={()=>show("You found something. But not the destination. 👀")}>✦</button><p>Some things are better discovered than explained.</p><span>— S</span></section><footer><span>MISSION STATUS: ACTIVE</span><span>◦</span><button onClick={()=>show("Good instincts. Still classified.")}>ACCESS DENIED</button></footer>{egg&&<div className="toast">{egg}</div>}</main>;
}